dataloaders:
  data_path: '../MIT_split/'
  input_size: 224
  batch_size: 32
  inference_batch_size: 1

output_path: 'results_ft/'

# Training Setting
optimizer:
  type: sgd
  params:
    momentum: 0.9
    weight_decay: 0.0001

model:
  name: 'ft_baseline'


# Callbacks Settings
wandb:
  project: 'task_0'
  entity: 'mcv-m3-g6'


lr_scheduler:
  type: constant
  params:
    base_lr: 0.001
    num_epochs: 20
    decay_rate: 0.96
    drop_every: 3


early_stopping:
  use: True
  patience: 6