dataloaders:
  data_path: '../MIT_small_train_1/'
  input_size: 224
  batch_size: 32
  inference_batch_size: 1

output_path: 'results_ft/'

# Training Setting
optimizer:
  type: sgd
  params:
    momentum: 0.9
    weight_decay: 0.0001


# Callbacks Settings
wandb:
  project: 'test-project'
  entity: 'mcv-m3-g6'

model_saving:
  output_path: '../'
  weights_only: True

lr_scheduler:
  type: constant
  params:
    base_lr: 0.001
    num_epochs: 20
    decay_rate: 0.9
    drop_every: 5


early_stopping:
  use: True
  patience: 5