dataloaders:
  data_path: '../data/MIT_small_train_1/'
  input_size: 224
  batch_size: 32
  inference_batch_size: 1
  data_augmentation:
    use: False
    rotation_range: 20
    width_shift_range: 0.2
    height_shift_range: 0.2
    shear_range: 0.2
    zoom_range: 0.2
    channel_shift_range: 0.2

output_path: 'results_ft/'
epochs: 50
# Training Setting
optimizer:
  type: sgd
  params:
    momentum: 0.9
    weight_decay: 0.0001

model:
  name: 'modified_mobilenet'
  pops: 0


# Callbacks Settings
wandb:
  project: 'task_1'
  entity: 'mcv-m3-g6'


lr_scheduler:
  type: constant
  params:
    base_lr: 0.005
    decay_rate: 0.2
    drop_every: 5


early_stopping:
  use: True
  patience: 15


